[package]
name = "gurobi"
version = "0.1.7"
authors = ["Yusuke Sasaki <y_sasaki@nuem.nagoya-u.ac.jp>"]
description = "An unofficial Rust API for Gurobi optimizer"
license = "MIT"
homepage = "https://github.com/ys-nuem/rust-gurobi"
repository = "https://github.com/ys-nuem/rust-gurobi.git"
documentation = "https://ys-nuem.github.io/rust-gurobi/doc/gurobi/index.html"

[dependencies]
itertools = "*"

[dependencies.gurobi-sys]
path = "./gurobi-sys"
version = "0.1.3"
